[package]
name = "rustmart"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
yew = "0.17"
yew-router="0.14.0"
wasm-bindgen="0.2"
anyhow="1.0.32"
serde={version = "*",features = ["derive"]}
